#!/bin/bash

set -e

if [[ -n "${CI}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Execute project linters and test suites.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        # Lint
        flake8 stacterm tests

        # Code formatting
        yapf -dpr stacterm tests

        # Code spelling
        codespell -I .codespellignore -f \
            stacterm/*.py stacterm/**/*.py \
            tests/*.py tests/**/*.py \
            docs/*.rst docs/**/*.rst \
            docs/*.ipynb docs/**/*.ipynb \
            scripts/* \
            *.py \
            *.md

        # Test suite with coverage enabled
        pytest -s --cov stacterm --cov-report term-missing
        coverage xml
    fi
fi
