#!/bin/bash

set -e

if [[ -n "${CI}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Execute project linters and test suites.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        # Lint
        flake8 stacterm tests

        # Code formatting
        yapf -dpr stacterm tests

        # Test suite with coverage enabled
        pytest -s --cov stacterm --cov-report term-missing
        coverage xml
    fi
fi
